# This is a basic workflow that is manually triggered

name: Client Manual Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  initialize:
    if: github.repository_owner == 'rare-idiots'
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client
    steps:
      - name: git clone
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: build
        run: npm run build

      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        run: |
          aws s3 cp \
          --recursive \
          --region ap-northeast-2 \
          public s3://hyeja-pdf-converter.wanzargen.me



