# This is a basic workflow that is manually triggered

name: Client Manual Workflow

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./client

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: npm install
        run: npm install

      - name: build
        run: REACT_APP_S3_ACCESS_KEY=$AWS_ACCESS_KEY_ID REACT_APP_S3_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY REACT_APP_S3_BUCKET_NAME=$AWS_BUCKET_NAME npm run build
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_BUCKET_NAME: "${{ secrets.AWS_BUCKET_NAME }}"

      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://hyeja-pdf-converter.wanzargen.me
