name: Server Manual Workflow

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./server

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: start
        uses: actions/checkout@v2

      - name: npm install
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          args: npm install

      - name: serverless
        uses: serverless/github-action@v1.53.0
        with:
          args: deploy -c serverless.yml -r ap-northeast-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # or if using SERVERLESS_ACCESS_KEY
          #  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
